<?php
	
	
	namespace app\admin\controller;
	
	
	use think\Controller;
	use think\Session;
	
	class Bace extends Controller
	{
		public  function  _initialize()
		{
			parent::_initialize(); // TODO: Change the autogenerated stub
			if(Session::has('user')){
				$this->error('请登录','admin/login/index');
				exit();
			}
		}
		
	}