<?php
	
	
	namespace app\admin\controller;
	
	
	use think\Controller;
	use think\Db;
	
	class Nav extends Controller
	{
		public function _initialize()
		{
			parent::_initialize(); // TODO: Change the autogenerated stub
		}

//		查看导航
		public function index(){
			return $this->fetch('index');
		}
//		展示插入页面
		public  function openinsert(){
			return view('openinsert');
		}
//		插入逻辑
		public function insert(){
			$method=$this->request->method();
			if($method!='POST'){
				return json(['code'=>404,'msg'=>'请求方式错误']);
			}
			$data=input('post.');
//			 验证规则
			$validate =validate('Nav');
			
			if(!$validate->scene('insert')->check($data)){
				return json(['code'=>404,'msg'=>$validate->getError()]);
			}
			$result=Db::table('nav') ->insert($data);
			if($result>0){
				return json(['code'=>200,'msg'=>'数据插入成功']);
			}
			else{
				return json(['code'=>404,'msg'=>'数据插入失败']);
			}
		               
		}
		
//		渲染数据
	public  function query(){
		$data=input('post.');
			$data=Db::table('nav')->select();
			$count=Db::table('nav')->count();
			return json(
				['code'=>0,
					'msg'=>'success',
					'data'=>$data,
					'count'=>$count,
					
				]);
	}
	public  function delete(){
		$method=$this->request->method();
		if($method!='POST'){
			return json(['code'=>404,'msg'=>'请求方式错误']);
		}
		$data=input('post.');
		$validate =validate('Nav');
		if(!$validate->scene('delete')->check($data)){
			return json(['code'=>404,'msg'=>$validate->getError()]);
		}
		$result=Db::table('nav')->where('id',$data['id'])->delete();
		if($result>0){
			return json(['code'=>200,'msg'=>'数据删除成功']);
		}
		else{
			return json(['code'=>404,'msg'=>'数据删除失败']);
		}
	}
		public  function update(){
			$method=$this->request->method();
			if($method!='POST'){
				return json(['code'=>404,'msg'=>'请求方式错误']);
			}
			$data=input('post.');
			$validate =validate('Nav');
			if(!$validate->scene('update')->check($data)){
				return json(['code'=>404,'msg'=>$validate->getError()]);
			}
			$result=Db::table('nav')->where('id',$data['id']) ->update([$data['field']=>$data['value']]);
			if($result>0){
				return json(['code'=>200,'msg'=>'数据更新成功']);
			}
			else{
				return json(['code'=>404,'msg'=>'数据更新失败']);
			}
		}
	}